# -*- coding: utf-8 -*-
"""KBCPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mw9KNn9POJFivK34kkkALNxXF1HXVmlo
"""

#KBC project

amount=[1000,5000,30000,120000,320000,1250000,2500000,5000000,7500000,100000000,700000000]
lifeline= 1

def question_1():
    global lifeline
    print("1.Grand Central Terminal, Park Avenue, New York is the worlds")
    print("options:")
    print("A:largest railway station")
    print("B:highest railway station")
    print("C: longest railway station")
    print("D:NonE of the above")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' : ")

    def answer1():
        if useranswer=="A" or useranswer=="a":
            print("You won the first step!, the wining amount is ", amount[0])
            print("lets move to Next question!")

        elif useranswer=="B" or useranswer=="b" or useranswer=="C" or useranswer=="c" or useranswer=="D" or useranswer=="d":
            print("Oops! Your given answer is Wrong ")
            exit()
    answer1()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("A:largest railway station")
                print("C: longest railway station")
                lifeline=0

                finalanswer=input("Enter your answer : ")
                if finalanswer=="A" or finalanswer=="a":
                    print("You won the first step!, the wining amount is ", amount[0])
                    print("lets move to Next question!")
                elif finalanswer=="C" or finalanswer=="c":
                    print("Oops! Your given answer is Wrong ")
                    exit()
            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_1()
        else:
            print("You have no lifeline left")
            return question_1()



question_1()

print()

def question_2():
    global lifeline
    print("2.Bahubali festival is related to")
    print("options:")
    print("A:Islam")
    print("B:Hinduism")
    print("C:Buddhism")
    print("D:Jainism")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' or if you wish to quit type quit: ")

    def answer2():
        if useranswer=="D" or useranswer=="D":
            print("You won !, the wining amount is ", amount[1])
            print("lets move to Next question!")

        elif useranswer=="B" or useranswer=="b" or useranswer=="C" or useranswer=="c" or useranswer=="A" or useranswer=="a":
            print("Oops! Your given answer is Wrong ")
            exit()

        elif useranswer=="Quit" or useranswer=="quit":
            quitquestion=input("Are you sure you want to quit Yes/No :")
            if quitquestion=="Yes" or quitquestion=="yes":
                print("Guess the correct answer !")
                print("2.Bahubali festival is related to")
                print("options:")
                print("A:Islam")
                print("B:Hinduism")
                print("C:Buddhism")
                print("D:Jainism")
                quitanswer=input("enter answer:")
                if quitanswer=="D" or quitanswer=="d":
                    print("Correct! you could have won ", amount[1])
                    print("But don't worry you have won ",amount[0])
                    exit()
                elif  quitanswer=="B" or quitanswer=="b" or quitanswer=="C" or quitanswer=="c" or quitanswer=="A" or quitanswer=="a":
                    print("You were wrong Better luck next time!")
                    print("But don't worry you have won ",amount[0])
                    exit()
    answer2()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("B:Buddhism")
                print("D:Jainism")
                lifeline= 0

                finalanswer=input("Enter your answer : ")
                if finalanswer=="D" or finalanswer=="d":
                    print("You won !, the wining amount is ", amount[1])
                    print("lets move to Next question!")
                elif finalanswer=="B" or finalanswer=="b":
                    print("Oops! Your given answer is Wrong ")
                    exit()
            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_2()
        else:
            print("you have no lifeline left")
            return question_2()

question_2()


print()

def question_3():
    global lifeline
    print("3.Which of the following gods is also known as 'Gauri Nandan'?")
    print("options:")
    print("A:Agni")
    print("B:Indra")
    print("C:Hanuman")
    print("D:Ganesha")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' or if you wish to quit type quit: ")
    def answer3():
        if useranswer=="D" or useranswer=="D":
            print("You won !, the wining amount is ", amount[2])
            print("lets move to Next question!")

        elif useranswer=="B" or useranswer=="b" or useranswer=="C" or useranswer=="c" or useranswer=="A" or useranswer=="a":
            print("Oops! Your given answer is Wrong ")
            exit()

        elif useranswer=="Quit" or useranswer=="quit":
            quitquestion=input("Are you sure you want to quit Yes/No :")
            if quitquestion=="Yes" or quitquestion=="yes":
                print("Guess the correct answer !")
                print("3.Which of the following gods is also known as 'Gauri Nandan'?")
                print("options:")
                print("A:Agni")
                print("B:Indra")
                print("C:Hanuman")
                print("D:Ganesha")
                quitanswer=input("enter answer:")
                if quitanswer=="D" or quitanswer=="d":
                    print("Correct! you could have won ", amount[2])
                    print("But don't worry you have won ",amount[1])
                    exit()
                elif  quitanswer=="B" or quitanswer=="b" or  quitanswer=="C" or quitanswer=="c" or quitanswer=="A" or quitanswer=="a":
                    print("You were wrong Better luck next time!")
                    print("But don't worry you have won ",amount[1])
                    exit()
    answer3()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("B:Indra")
                print("D:Ganesha")
                lifeline= 0


                finalanswer=input("Enter your answer : ")
                if finalanswer=="D" or finalanswer=="d":
                    print("You won !, the wining amount is ", amount[2])
                    print("lets move to Next question!")
                elif finalanswer=="B" or finalanswer=="b":
                    print("Oops! Your given answer is Wrong ")
                    exit()
            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_3()
        else:
            print("Oops you dont have any lifeline left")
            return question_3()
question_3()

print()

def question_4():
    global lifeline
    print("4.Which day is observed as World Standards Day?")
    print("options:")
    print("A:Nov 15")
    print("B:Oct 14")
    print("C:June 26")
    print("D:Jan 26")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' or if you wish to quit type quit: ")
    def answer4():
        if useranswer=="B" or useranswer=="b":
            print("You won !, the wining amount is ", amount[3])
            print("lets move to Next question!")

        elif useranswer=="D" or useranswer=="D" or useranswer=="C" or useranswer=="c" or useranswer=="A" or useranswer=="a":
            print("Oops! Your given answer is Wrong ")
            exit()

        elif useranswer=="Quit" or useranswer=="quit":
            quitquestion=input("Are you sure you want to quit Yes/No :")
            if quitquestion=="Yes" or quitquestion=="yes":
                print("Guess the correct answer !")
                print("4.Which day is observed as World Standards Day?")
                print("options:")
                print("A:Nov 15")
                print("B:Oct 14")
                print("C:June 26")
                print("D:Jan 26")
                quitanswer=input("enter answer:")
                if quitanswer=="D" or quitanswer=="d":
                    print("Correct! you could have won ", amount[3])
                    print("But don't worry you have won ",amount[2])
                    exit()
                elif  quitanswer=="B" or quitanswer=="b" or quitanswer=="C" or quitanswer=="c" or quitanswer=="A" or quitanswer=="a":
                    print("You were wrong Better luck next time!")
                    print("But don't worry you have won ",amount[2])
                    exit()
    answer4()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("B:Oct 14")
                print("A:Nov 15")
                lifeline= 0

                finalanswer=input("Enter your answer : ")
                if finalanswer=="B" or finalanswer=="b":
                    print("You won !, the wining amount is ", amount[3])
                    print("lets move to Next question!")
                elif finalanswer=="A" or finalanswer=="a":
                    print("Oops! Your given answer is Wrong ")
                    exit()

            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_4()



        else:
            print("You have no lifeline left")
            return question_4()
question_4()

print()

def question_5():
    global lifeline
    print("5.Which day is observed as Sports Day every year?")
    print("options:")
    print("A:29th August")
    print("B:2nd October")
    print("C:26th July")
    print("D:22nd April")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' or if you wish to quit type quit: ")

    def answer5():
        if useranswer=="A" or useranswer=="a":
            print("You won !, the wining amount is ", amount[4])
            print("lets move to Next question!")

        elif useranswer=="D" or useranswer=="D" or useranswer=="C" or useranswer=="c" or useranswer=="B" or useranswer=="b":
            print("Oops! Your given answer is Wrong ")
            exit()

        elif useranswer=="Quit" or useranswer=="quit":
            quitquestion=input("Are you sure you want to quit Yes/No :")
            if quitquestion=="Yes" or quitquestion=="yes":
                print("Guess the correct answer !")
                print("5.Which day is observed as Sports Day every year?")
                print("options:")
                print("A:29th August")
                print("B:2nd October")
                print("C:26th July")
                print("D:22nd April")
                quitanswer=input("enter answer:")
                if quitanswer=="A" or quitanswer=="a":
                    print("Correct! you could have won ", amount[4])
                    print("But don't worry you have won ",amount[3])
                    exit()
                elif  quitanswer=="B" or quitanswer=="b" or quitanswer=="C" or quitanswer=="c" or quitanswer=="D" or quitanswer=="d":
                    print("You were wrong Better luck next time!")
                    print("But don't worry you have won ",amount[3])
                    exit()
    answer5()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("A:29th August")
                print("C:26th July")
                lifeline= 0

                finalanswer=input("Enter your answer : ")
                if finalanswer=="A" or finalanswer=="a":
                    print("You won !, the wining amount is ", amount[4])
                    print("lets move to Next question!")
                elif finalanswer=="C" or finalanswer=="c":
                    print("Oops! Your given answer is Wrong ")
                    exit()
            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_5()
        else:
            print("You have no lifeline left")
            return question_5()

question_5()

print()

def question_6():
    global lifeline
    print("6.Which day is observed as World Health?")
    print("options:")
    print("A:May 15")
    print("B:April 28")
    print("C:April 7")
    print("D:22nd April")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' or if you wish to quit type quit: ")

    def answer6():
        if useranswer=="C" or useranswer=="c":
            print("You won !, the wining amount is ", amount[5])
            print("lets move to Next question!")

        elif useranswer=="D" or useranswer=="D" or useranswer=="A" or useranswer=="a" or useranswer=="B" or useranswer=="b":
            print("Oops! Your given answer is Wrong ")
            exit()

        elif useranswer=="Quit" or useranswer=="quit":
            quitquestion=input("Are you sure you want to quit Yes/No :")
            if quitquestion=="Yes" or quitquestion=="yes":
                print("Guess the correct answer !")
                print("6.Which day is observed as World Health?")
                print("options:")
                print("A:May 15")
                print("B:April 28")
                print("C:April 7")
                print("D:22nd April")
                quitanswer=input("enter answer:")
                if quitanswer=="C" or quitanswer=="c":
                    print("Correct! you could have won ", amount[5])
                    print("But don't worry you have won ",amount[4])
                    exit()
                elif  quitanswer=="B" or quitanswer=="b" or quitanswer=="A" or quitanswer=="a" or quitanswer=="D" or quitanswer=="d":
                    print("You were wrong Better luck next time!")
                    print("But don't worry you have won ",amount[4])
                    exit()
    answer6()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("A:May 15")
                print("C:April 7")
                lifeline= 0

                finalanswer=input("Enter your answer : ")
                if finalanswer=="C" or finalanswer=="c":
                    print("You won !, the wining amount is ", amount[5])
                    print("lets move to Next question!")
                elif finalanswer=="A" or finalanswer=="a":
                    print("Oops! Your given answer is Wrong ")
                    exit()
            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_6()
        else:
            print("You have no lifeline left")
            return question_6()


question_6()

print()

def question_7():
    global lifeline
    print("7.Which of the following is an Island country?")
    print("options:")
    print("A:Maldives")
    print("B:Yemen")
    print("C:Peru")
    print("D:Oman")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' or if you wish to quit type quit: ")

    def answer7():
        if useranswer=="A" or useranswer=="a":
            print("You won !, the wining amount is ", amount[6])
            print("=====================================")
            print("lets move on  to the Final  question!")
            print("===============7crore===============")

        elif useranswer=="D" or useranswer=="D" or useranswer=="C" or useranswer=="c" or useranswer=="B" or useranswer=="b":
            print("Oops! Your given answer is Wrong ")
            exit()

        elif useranswer=="Quit" or useranswer=="quit":
            quitquestion=input("Are you sure you want to quit Yes/No :")
            if quitquestion=="Yes" or quitquestion=="yes":
                print("Guess the correct answer !")
                print("7.Which of the following is an Island country?")
                print("options:")
                print("A:Maldives")
                print("B:Yemen")
                print("C:Peru")
                print("D:Oman")
                quitanswer=input("enter answer:")
                if quitanswer=="A" or quitanswer=="a":
                    print("Correct! you could have won ", amount[6])
                    print("But don't worry you have won ",amount[5])
                    exit()
                elif  quitanswer=="B" or quitanswer=="b" or quitanswer=="C" or quitanswer=="c" or quitanswer=="D" or quitanswer=="d":
                    print("You were wrong Better luck next time!")
                    print("But don't worry you have won ",amount[5])
                    exit()
    answer7()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("A:Maldives")
                print("C:Peru")
                lifeline= 0

                finalanswer=input("Enter your answer : ")
                if finalanswer=="A" or finalanswer=="a":
                    print("You won !, the wining amount is ", amount[6])
                    print("=====================================")
                    print("lets move on  to the Final  question!")
                    print("===============7crore===============")
                elif finalanswer=="C" or finalanswer=="c":
                    print("Oops! Your given answer is Wrong ")
                    exit()
            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_7()
        else:
            print("You have no lifeline left")
            return question_7()

question_7()

print()

def question_8():
    global lifeline
    print("8.Since 2002, what is the currency of Greece?")
    print("options:")
    print("A:Drachma")
    print("B:Peso")
    print("C:Lira")
    print("D:Euro")
    useranswer=input("Enter your answer or you if you want to use lifeline type 'help' or if you wish to quit type quit: ")

    def answer8():
        if useranswer=="C" or useranswer=="c":
            print("You won !, the wining amount is ", amount[10])
            print("You won 7 crore Congratulations!!!!!!!!!!!!")


        elif useranswer=="D" or useranswer=="D" or useranswer=="A" or useranswer=="a" or useranswer=="B" or useranswer=="b":
            print("Oops! Your given answer is Wrong ")
            exit()

        elif useranswer=="Quit" or useranswer=="quit":
            quitquestion=input("Are you sure you want to quit Yes/No :")
            if quitquestion=="Yes" or quitquestion=="yes":
                print("8.Since 2002, what is the currency of Greece?")
                print("options:")
                print("A:Drachma")
                print("B:Peso")
                print("C:Lira")
                print("D:Euro")
                print("Guess the correct answer :")
                quitanswer=input("enter answer:")
                if quitanswer=="C" or quitanswer=="c":
                    print("Correct! you could have won ", amount[10])
                    print("But don't worry you have won ",amount[6])
                    exit()
                elif  quitanswer=="B" or quitanswer=="b" or quitanswer=="A" or quitanswer=="a" or quitanswer=="D" or quitanswer=="d":
                    print("You were wrong Better luck next time!")
                    print("But don't worry you have won ",amount[6])
                    exit()
    answer8()

    if useranswer=="Help" or useranswer=="help":
        if lifeline:
            lifelineanswer=input("You have One lifeline that is 50-50 , if you wish to continue Yes/No? ")
            if lifelineanswer=="Yes" or lifelineanswer=="yes":
                print("Your remaining options are---")
                print("C:Lira")
                print("D:Euro")
                lifeline= -1

                finalanswer=input("Enter your answer : ")
                if finalanswer=="C" or finalanswer=="c":
                    print("You won !, the wining amount is ", amount[10])
                    print("You won 7 crore Congratulations!!!!!!!!!!!!")

                elif finalanswer=="D" or finalanswer=="d":
                    print("Oops! Your given answer is Wrong ")
                    exit()
            elif lifelineanswer=="No" or lifelineanswer=="no":
                question_8()
        else:
            print("You have no lifeline left")
            return question_8()


question_8()